services:
  - type: web
    name: mediom-backend
    runtime: node
    rootDir: backend
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm run start
    plan: free
